---
title: "task-4-kings"
author: "Kings Group"
date: "10/21/2020"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


```{r read data, echo=FALSE, message=FALSE, warning=FALSE}
library(readr)
library(tidyverse)
library(tm)
library(wordcloud)
library(RColorBrewer)
intro_survey <- read_csv("intro-survey.csv")
```

# Descriptive stats of survey data
## Programming Languages
The graph below shows the distribution of programming language skills by group. 
```{r programming languages, echo=FALSE}
intro_survey %>% 
  select(l_r:l_web, cgroup) %>% 
  pivot_longer(-cgroup) %>% 
  count(cgroup, name, value) %>% 
  ggplot(aes(value, n, fill = cgroup)) +
  geom_col() +
  facet_grid(~ name) +
  scale_fill_viridis_d()

```

Word cloud of the familiarity of concepts

```{r cloud generation, echo=FALSE, warning=FALSE, message=FALSE}
toSpace <- content_transformer(function (x , pattern ) gsub(pattern, " ", x))
corpus = intro_survey %>% 
  select(general) %>%
  unlist() %>%
  as.vector() %>%
  VectorSource() %>%
  Corpus() %>%
  tm_map(toSpace, "vs.") %>%
  tm_map(toSpace, ",") %>%
  TermDocumentMatrix() %>%
  as.matrix() %>%
  rowSums()

freq_table <- data.frame(word = names(corpus),
                         freq = corpus)
set.seed(1)
wordcloud(words = freq_table$word, 
          freq = freq_table$freq, 
          min.freq = 1,
          max.words=200,
          random.order=FALSE, 
          rot.per=0.3, 
          colors=brewer.pal(8, "Dark2"))
```
